# Generated by Django 5.0.6 on 2024-06-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasingcontract',
            name='status',
            field=models.CharField(choices=[('processing', 'В обробці'), ('completed', 'Виконаний'), ('in_progress', 'Виконується'), ('cancelled', 'Відмінений')], default='processing', max_length=20, verbose_name='Status'),
        ),
    ]
