# Generated by Django 5.0.6 on 2024-06-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_leasingcontract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasingcontract',
            name='status',
            field=models.CharField(choices=[('Processing', 'В обробці'), ('Completed', 'Виконаний'), ('In_progress', 'Виконується'), ('Cancelled', 'Відмінений')], default='processing', max_length=20, verbose_name='Status'),
        ),
    ]
