# Generated by Django 5.0.6 on 2024-05-27 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_discount_alter_car_color_alter_car_photo'),
        ('leasing', '0002_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leasingcontract',
            options={'verbose_name': 'Leasing Contract', 'verbose_name_plural': 'Leasing Contracts'},
        ),
        migrations.RemoveField(
            model_name='leasingcontract',
            name='car_code',
        ),
        migrations.AddField(
            model_name='leasingcontract',
            name='car',
            field=models.ForeignKey(default='Chrysler 300', on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Payment'),
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='service_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.servicepackage', verbose_name='Service Package'),
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='leasing.servicepackage', verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
