# Generated by Django 5.0.6 on 2024-06-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_alter_leasingcontract_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='package',
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='services',
            field=models.ManyToManyField(related_name='service_packages', to='leasing.service', verbose_name='Services'),
        ),
    ]
