# Generated by Django 5.0.6 on 2024-06-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_alter_leasingcontract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasingcontract',
            name='status',
            field=models.CharField(choices=[('Processing', 'В обробці'), ('Completed', 'Виконаний'), ('In progress', 'Виконується'), ('Cancelled', 'Відмінений'), ('Сonfirmed', 'Підтверджений')], default='processing', max_length=20, verbose_name='Status'),
        ),
    ]
