# Generated by Django 5.0.6 on 2024-06-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('engine_capacity', models.DecimalField(decimal_places=1, help_text='Engine capacity in liters', max_digits=4, verbose_name='Engine Capacity')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=10, verbose_name='Fuel Type')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic')], max_length=15, verbose_name='Transmission')),
                ('mileage', models.PositiveIntegerField(help_text='Mileage in kilometers', verbose_name='Mileage')),
                ('drive_type', models.CharField(choices=[('fwd', 'Front-Wheel Drive'), ('rwd', 'Rear-Wheel Drive'), ('awd', 'All-Wheel Drive')], max_length=10, verbose_name='Drive Type')),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('grey', 'Grey')], max_length=50, verbose_name='Color')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/deps/images/cars/', verbose_name='Photo')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount in percentage', max_digits=5, null=True, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ('id',),
            },
        ),
    ]
