# Generated by Django 5.0.6 on 2024-05-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_alter_car_code_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount in percentage', max_digits=5, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('grey', 'Grey')], max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/deps/images/cars/', verbose_name='Photo'),
        ),
    ]
